name:                libmdbx
version:             0.2.1.1
github:              fjvallarino/libmdbx-hs
license:             BSD3
author:              Francisco Vallarino
maintainer:          fjvallarino@gmail.com
copyright:           2021 Francisco Vallarino

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Bindings for libmdbx, an embedded key/value store
category:            Database

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
  Haskell bindings for [libmdbx](https://github.com/erthink/libmdbx).

  See documentation in the main module or check the
  <https://github.com/fjvallarino/libmdbx-hs#readme README>
  on GitHub.

dependencies:
  - base >= 4.12 && < 5
  - binary >= 0.8 && < 0.11
  - bytestring >= 0.10 && < 0.12
  - data-default >= 0.5 && < 0.8
  - mtl >= 2.1 && < 2.3
  - store >= 0.5 && < 0.8
  - store-core >= 0.4 && < 0.5
  - text >= 1.2 && < 1.3
  - transformers >= 0.5 && < 0.7

library:
  source-dirs: src
  include-dirs: cbits/libmdbx
  install-includes:
    - cbits/libmdbx/mdbx.h
  c-sources:
    - cbits/libmdbx/mdbx.c
  build-tools: c2hs

executables:
  libmdbx-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - libmdbx

tests:
  libmdbx-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - directory >= 1.3 && < 1.4
      - hspec >= 2.4 && < 3.0
      - HUnit >= 1.6 && < 1.7
      - libmdbx
