name:                libmdbx
version:             0.1.0.4
github:              fjvallarino/libmdbx-hs
license:             BSD3
author:              Francisco Vallarino
maintainer:          fjvallarino@gmail.com
copyright:           2021 Francisco Vallarino

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Bindings for libmdbx, an embedded key/value store
category:            Database

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
  Haskell bindings for [libmdbx](https://github.com/erthink/libmdbx).

  See documentation in the main module or check the
  <https://github.com/fjvallarino/libmdbx-hs#readme README>
  on GitHub.

dependencies:
- base >= 4.12 && < 5
- mtl >= 2.1 && < 2.3
- text >= 1.2 && < 1.3

library:
  source-dirs: src
  include-dirs: cbits/libmdbx
  install-includes:
  - cbits/libmdbx/mdbx.h
  c-sources:
  - cbits/libmdbx/mdbx.c
  build-tools: c2hs

executables:
  libmdbx-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - libmdbx
    - bytestring >= 0.10 && < 0.12
    - store >= 0.5 && < 0.8

tests:
  libmdbx-hs-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - libmdbx
